# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: DeepChain GmbH
subtitle: Professional Blockchain
email: info@deepchain.de
description: >- # this means to ignore newlines until "baseurl:"
  DeepChain GmbH is a German high-tech startup focusing on blockchain development and consultancy.

author: DeepChain GmbH
avatar: assets/images/avatar.png

baseurl: "" # the subpath of your site, e.g. /blog
url: "http://deepchain.de" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: DeepChainDE
github_username:  deepchainde

github_url: https://github.com/deepchainde
twitter_url: https://twitter.com/DeepChainDE

# Build settings
markdown: kramdown
#theme: minima
theme: jekyll-theme-prologue
remote_theme: chrisbobbe/jekyll-theme-prologue


# Google Analytics Tracking ID goes here:
google_analytics: UA-121112764-1

collections: [sections]

plugins:
  - jekyll-feed


# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/


